// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vox.Data;

#nullable disable

namespace Vox.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230406232530_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vox.Data.Entities.CreateChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("category_id");

                    b.Property<long>("ChannelId")
                        .HasColumnType("bigint")
                        .HasColumnName("channel_id");

                    b.Property<long>("GuildId")
                        .HasColumnType("bigint")
                        .HasColumnName("guild_id");

                    b.HasKey("Id")
                        .HasName("pk_create_channel");

                    b.HasIndex("GuildId")
                        .HasDatabaseName("ix_create_channel_guild_id");

                    b.HasIndex("GuildId", "CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_create_channel_guild_id_category_id");

                    b.ToTable("create_channel");
                });

            modelBuilder.Entity("Vox.Data.Entities.UserChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ChannelLimit")
                        .HasColumnType("integer")
                        .HasColumnName("channel_limit");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel_name");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("permissions");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_channel");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_channel_user_id");

                    b.ToTable("user_channel");
                });
#pragma warning restore 612, 618
        }
    }
}
